### ISSUE TITLE
2020-04-20 crash bug

### ISSUE THREAD

**Issue by inada-s** [inada-s/zdxsv#38]
crash bug
```
lobby_1         | panic: runtime error: invalid memory address or nil pointer dereference
lobby_1         | [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8c7ec5]
lobby_1         |
lobby_1         | goroutine 24 [running]:
lobby_1         | zdxsv/pkg/lobby/model.(*Room).GetEntryUserCount(0x0, 0x100000000000010)
lobby_1         |       /work/pkg/lobby/model/room.go:85 +0x5
lobby_1         | zdxsv/pkg/lobby.(*App).OnEntryRoomMatch(0xc0000e8940, 0xc000129680, 0xc00200)
lobby_1         |       /work/pkg/lobby/app_core.go:896 +0x55
lobby_1         | zdxsv/pkg/lobby.glob..func69(0xc000129680, 0xc000dc09f0)
lobby_1         |       /work/pkg/lobby/msg_room.go:274 +0x15d
lobby_1         | zdxsv/pkg/lobby.(*App).Serve(0xc0000e8940)
lobby_1         |       /work/pkg/lobby/app.go:182 +0x6b1
lobby_1         | created by main.mainLobby
lobby_1         |       /work/src/zdxsv/lobby.go:13 +0x5a
```

**Comment by inada-s** [comment]
I'll install this.
https://github.com/mitchellh/panicwrap
